# Welcome to Jekyll!


# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: Oakley Dye
description: Full Stack Software Engineer
owner:
  name: Oakley Dye # or company name
  url: "http://oakleydye.github.io/oakley" # your URL
first_published: 2020 # if migrating another site, the year of your first publish
                      # Must be a 4-digit integer year (math is used on it)
url: "http://oakleydye.github.io" # the base hostname & protocol for this site
baseurl: "/oakley" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.
lang: en-us # used in HTML lang attributes

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Hi there!
  text: >
   My name is Oakley and I’m a software developer at 
   Conservice based in Logan, UT and an entrepreneur, 
   designer, and developer at Anasi Business Solutions. 
   By day, you can find me developing enterprise software 
   in C# and SQL for the Utility Experts. By night, I’m 
   typically working on client websites, creating an 
   awesome logo, hanging out with family and friends, 
   or working on my Jeep. 
   
   Thanks for checking out my site, 
   hope to be in contact with you soon! 


# - displayed at the bottom
closing-head: Questions?
closing-para: >
  Feel free to reach out to me about anything. I'm down to hear
  about employment opportunities, to freelance, mentor/tutor,
  or just chat! The best way to get a hold of me is through Twitter,
  but I'll respond to emails as well.  


# on all pages (and the first three you list display with greeting, if included)
social:
  linkedin-square: https://linkedin.com/in/oakley-dye
  twitter: https://twitter.com/oakleydye
  email: /contact/ # you can configure and use this contact page or use your email addy
  github: https://github.com/oakleydye
  facebook-official: https://facebook.com/oakley.dye
  #google-plus-square: https://plus.google.com/u/0/+_username_
  #flickr:
  instagram: https://instagram.com/oakley_dye
  #youtube-square:
  #spotify:
  stack-overflow: https://stackoverflow.com/users/14506946/oakley
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# - title for your blog's featured posts
features-title: Featured topics

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# Github pages posts future posts by default.
# You'll want to move the user guide posts to _drafts if you set this to true.
future: false

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
